name: CI/CD using github actions & docker

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  CI-CD:
    runs-on: ubuntu-latest
    steps:
      - name: make .env
        run: |
          touch .env
          echo "CSV_URL=${{ secrets.CSV_URL }}\n" >> .env
          echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}\n" >> .env
        shell: bash

      # docker build & push to production
      - name: Docker build & push to prod
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -f Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/docker-odc-bot .
          docker push ${{ secrets.DOCKER_USERNAME }}/docker-odc-bot

      - name: Deploy to prod
        uses: appleboy/ssh-action@master
        id: deploy-prod
        with:
          host: ${{ secrets.HOST_PROD }} # EC2 퍼블릭 IPv4 DNS
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          envs: GITHUB_SHA
          script: |
            sudo docker ps
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/docker-odc-bot
            sudo docker run -d -p 8082:8082 ${{ secrets.DOCKER_USERNAME }}/docker-odc-bot
            sudo docker image prune -f
